config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :item_orders
  resources :carts
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/about' => 'items#about'
  resources :items, only: [:index, :show, :update, :edit, :create, :new, :destroy]
  resources :photos, only: [:new, :create, :show]


  namespace :admin do
    resources :items, only: [:new, :create, :show, :edit, :destroy, :update]
    resources :photos, only: [:new, :create, :show]
    
  end
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :cart
  references :item 

  def total_price
    item.price.to_i * quantity.to_i
  end
end

app/controllers/item_orders_controller.rb
class ItemOrdersController < ApplicationController
  #include CurrentCart
  #before_action :set_item_order, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create] 

  # GET /item_orders
  # GET /item_orders.json
  def index
    @item_orders = ItemOrder.all
  end

  # GET /item_orders/1
  # GET /item_orders/1.json
  def show
    puts "DFLKJL:KJSDFLJ:LSDFJLSDJFLSDJKFLSDJFL:SDFKJL:SDFJLSJDFLJKDLFJSDFL"
  end

  # GET /item_orders/new
  def new
    @item_order = ItemOrder.new
  end

  # GET /item_orders/1/edit
  def edit
  end

  # POST /item_orders
  # POST /item_orders.json
  def create
    item = Item.find(params[:item_id])
    @item_order = @cart.add_item(item)

    respond_to do |format|
      if @item_order.save
        format.html { redirect_to @item_order.cart, notice: 'Item added to cart.' }
        format.json { render :show, status: :created, location: @item_order }
      else
        format.html { render :new }
        format.json { render json: @item_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_orders/1
  # PATCH/PUT /item_orders/1.json
  def update
    respond_to do |format|
      if @item_order.update(item_order_params)
        format.html { redirect_to @item_order, notice: 'Item order was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_order }
      else
        format.html { render :edit }
        format.json { render json: @item_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_orders/1
  # DELETE /item_orders/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @item_order.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: 'Item order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_item_order
    #   @item_order = ItemOrder.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_order_params
      params.require(:item_order).permit(:item_id)
    end
end

app/helpers/item_orders_helper.rb
module ItemOrdersHelper
end

app/views/item_orders/_form.html.erb
<%= simple_form_for(@item_order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :item %>
    <%= f.association :cart %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/item_orders/_item_order.html.erb
<div class="columns align-items-center">
  <div class="column is-1">
    <%= item_order.quantity %>
  </div>

  <div class="column is-2">
    <figure class="is-128x128 image">
      <%= image_tag item.photo.to_s %>
    </figure>
  </div>

  <div class="column is-9">
    <strong><%= item_order.item.summary %></strong>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <%= truncate(item_order.item.description, length: 140) %>
      </div>
      <div class="column is-3 has-text-right">
        <strong class="f4"><%= number_to_currency(item_order.total_price) %></strong>
      </div>
    </div>
  </div>
</div>

<div class="has-text-right">
  <%= link_to 'Remove Item', item_order, method: :delete, data: { confirm: "Are you sure?" }, class: 'card-link' %>
</div>

<br />

app/views/item_orders/edit.html.erb
<h1>Editing Item Order</h1>

<%= render 'form', item_order: @item_order %>

<%= link_to 'Show', @item_order %> |
<%= link_to 'Back', item_orders_path %>

app/views/item_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Cart</h1>

<%= puts "---------NOT IN THE TABLE-------" %>
<%= puts @item %>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= puts @item %>

  <tbody>
    <%= puts "----------------IN THE TABLE----------------------------" %>
    <%= puts @item %>
    <% @item_orders.each do |item_order| %>
      <tr>
        <td><%= item_order.item %></td>
        <td><%= item_order.cart %></td>
        <td><%= link_to 'Show', item_order %></td>
        <td><%= link_to 'Edit', edit_item_order_path(item_order) %></td>
        <td><%= link_to 'Destroy', item_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Order', new_item_order_path %>

app/views/item_orders/new.html.erb
<h1>New Item Order</h1>

<%= render 'form', item_order: @item_order %>

<%= link_to 'Back', item_orders_path %>

app/views/item_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item %>
</p>



<%= link_to 'Edit', edit_item_order_path %> |
<%= link_to 'Back', item_orders_path %>