config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :item_orders
  resources :carts
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/about' => 'items#about'
  resources :items, only: [:index, :show, :update, :edit, :create, :new, :destroy]
  resources :photos, only: [:new, :create, :show]


  namespace :admin do
    resources :items, only: [:new, :create, :show, :edit, :destroy, :update]
    resources :photos, only: [:new, :create, :show]
    
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :admin
  has_many :photos
  mount_uploader :photo, ImageUploader
  
  

  validates :summary, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index

    @item = Item.all 
  end

  def new

    @item = Item.new
  end

  def create
    anotherHash = {:admin_id=> 1}
    newDbEntry=anotherHash.merge(item_params)
    @item = Item.new(newDbEntry)
      if @item.save
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
    end
  end

  def show
    @items = Item.find(params[:id])
    @photo = Photo.new 

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to root_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end

  private

   def item_params
     params.require(:item).permit(:summary, :description, :price, :photo)
   end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    anotherHash = {:admin_id=> 1}
    newDbEntry=anotherHash.merge(item_params)
    @item = Item.new(newDbEntry)
      if @item.save
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
    end
    @photo = Photo.new
  end

  def show
    @item = Item.find(params[:id])
    #@photo = Photo.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to root_path
  end

  def destroy
    @item = Item.find(params[:id])
  end

  private

   def item_params
     params.require(:item).permit(:summary, :description, :price, :photo)
   end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/about.html.erb
<div class="col-10 offset-3" style="max-width: fit-content;">
  <div class="about-card" style="width: 40rem;">
    <%= image_tag 'tina.jpg', class: 'about-card-img-top center' %>
    <div class="card-body center">
      <h5 class="about-card-title">Colorful Creations by Tinamarie Romero-Margaillan</h5>
      <p class="about-card-text">Hello, and thank you for stopping by and looking at my website.  I live in Tucson Arizona a little ways out of the city, where every evening I can sit and watch the most beautiful sunsets.  Each sunset is unique in the colors I see, and I love color. Bright beautiful colors which inspired me in my painting methods.  I love to “refurbish “ pieces that have no life to them anymore.  I shop at local thrift stores, yard sales, estate sales, etc, and buy the items no longer wanted and giving them a whole new look.  I also create unique suncatchers to hang out in your trees, patio, or in your windows.  I use only glass beads that really catch the sun and really catch your eye. My suncatchers are one of a kind and make wonderful gifts for any occasion!</p>
      <p class="about-card-text center" style="font-size: 30px"><b>Upcoming Art Shows:</b><p class="about-card-text center">Harvest Festival</p><p class="about-card-text center">Hereford, AZ</p><p class="about-card-text center">Oct 26, 2019</p><p class="about-card-text center">10a - 4p</p></p>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h2 class="jumbotron-heading">Welcome to Colorful Creations by Tinamarie!</h2>
      <p class="lead">
        All items you see below are uniquely hand-painted or hand-crafted. If you see something you like, please select "Place Order" to send me an email. To learn more about me and find out about upcoming art shows I will be at, select "About".
      </p>
  </div>
</section>

<div class="row" style="padding-right: 5.2rem;">
  <% @items.each do |item| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <!-- <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <%= image_tag item.photo.to_s, class: 'card-img-top' %>
            </div>
            <div class="carousel-item">
              <%= image_tag item.photo.to_s, class: 'card-img-top' %>
            </div>
            <div class="carousel-item">
              <%= image_tag item.photo.to_s, class: 'card-img-top' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div> -->
        <%= image_tag item.photo.to_s, class: 'card-img-top' %>
        <br /><br />
        <h5 class="card-title"><%= item.summary %></h5><br />
        <h6 class="card-subtitle mb-2 text-muted">&#36;<%= item.price %>0</h6><br />
        <%= link_to 'Details', item_path(item.id), class: 'card-link' %>
        <br />
        <br />
        <% if admin_signed_in? %>
          <%= link_to 'Edit', edit_admin_item_path(item.id), class: 'card-link' %>
          <%= link_to 'Delete', admin_item_path(item.id), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'card-link' %>
        <% end %>
      </div>
    </div>
    <hr />
  <% end %>
</div>




  
   

app/views/items/show.html.erb
<div class="col-10 offset-3">
  <%# @items.each do |item| %>
    <div class="card" style="width: 40rem;">
      <div class="card-body center">
        <%= image_tag @item.photo.to_s, class: 'card-img-top center' %>
        <br /><br />
        <h5 class="card-title"><%= @item.summary %></h5><br /><br />
        <h5 class="card-subtitle"><%= @item.description %></h5><br /><br />
        <h6 class="card-subtitle mb-2 text-muted">&#36;<%= @item.price %>0</h6><br />
        <% if admin_signed_in? %>
          <%= link_to 'Edit', edit_admin_item_path(item_url), class: 'card-link' %>
          <%= link_to 'Delete', admin_item_path(@item.id), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'card-link' %>
        <%# end %>
      </div>
    </div>
    <hr />
  <% end %>
</div>