config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :item_orders
  resources :carts
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/about' => 'items#about'
  resources :items, only: [:index, :show, :update, :edit, :create, :new, :destroy]
  resources :photos, only: [:new, :create, :show]


  namespace :admin do
    resources :items, only: [:new, :create, :show, :edit, :destroy, :update]
    resources :photos, only: [:new, :create, :show]
    
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colorful Creations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.jpg' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Lobster+Two:700|Niconne|Spirax&display=swap');
      @import url('https://fonts.googleapis.com/css?family=Merienda&display=swap');
    </style>
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-dark bg-dark">
      <a style="color: #ed7b84;" class="navbar-brand" href="#">Colorful Creations by Tinamarie</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Place Order', new_order_path, class: 'nav-link' %>
          </li>

        </ul>
    

        </form>
      </div>
    </nav>

    <% if notice.present? %>
        <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>

        <%= yield %>
    </div>

    <div id="footer">
      <div class="column" style="float: left;">
        <div class="row">
          <div class="footer-item" style="text-align: center; padding-left: 1100px; padding-right: 100px;">
            <p>Quesstions? Comments? Special requests?</p>
            <p>Email me at:</p>
            <p>bitburg1974@gmail.com</p> 
          </div>
          <% if admin_signed_in? %>
            <div class="footer-item" style="text-align: right; padding-left: 700px">
              <%= link_to 'Add New Item', new_admin_item_path, class: 'nav-link' %>
              <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
              <p>&copy;Adeline Margaillan</p>
            </div>
          <% else %>
            <div class="footer-item" style="text-align: right; padding-left: 700px">
              <%= link_to 'Admin Login', new_admin_session_path, class: 'nav-link' %> 
              <p>&copy;Adeline Margaillan</p>
            </div> 
          <% end %>
          
          <div class="footer-item">
            
          </div>
        </div>
      </div>
    </div>
    <script>setTimeout(function(){ document.querySelector(".notice").style.display="none"; }, 3000);</script>
  </body>
</html>